# Generated by Django 5.2.8 on 2025-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_useriamges_userimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='login_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
